# API to use for scoring. Possible values: "local", "anthropic"
#
# For anthropic, specify the ANTHROPIC_API_KEY environment variable with an API key.
#api: local
#endpoint: http://localhost:1234/v1
#model: ministral-3-8b-instruct-2512@8bit

api: anthropic
model: claude-sonnet-4-5-20250929

# How many times to run the scoring.
# Higher values increase confidence but also cost and time.
repetitions: 3
